### PR TITLE
Tidy up and bump Node

### PR DESCRIPTION
**Pull request by dcousens**
- [x] Adhere `tests/` to `standard`

### CODE REVIEW

**Comment by dcousens** [comment]
@dominictarr this should be good to go

**Comment by dominictarr** [comment]
I have removed my self as maintainer as I no longer use this. Please do whatever!

**Comment by dcousens** [comment]
Published as  6.1.3

**Comment by dcousens** [comment]
@dominictarr what do we do if no one wants to maintain this anymore?

**Comment by dominictarr** [comment]
I transferred a bunch of my modules to https://www.npmjs.com/~nopersonsmodules a while back. I created that account and forgot the password (including to the email it's set up with). After transferring, remove your self as maintainer. Then, if someone makes a PR I just say, "sorry I can't publish this even if I wanted to, please fork and republish" I used to feel bad telling people I didn't care about their PR, but with this new system it isn't personal. Also, set the repo "archived" on github.

**Pull request merged**
